### ISSUE TITLE
raise ValueError("No records found in handle")

### ISSUE THREAD

**Issue by Deco313** [MikeWLloyd/proc-multi-probe-hit#2]
Hi,
 Similar to https://github.com/faircloth-lab/phyluce/issues/87 I have loads of UCE loci that hit multiple contigs and multiple contigs that match UCE loci. I do not think these are paralogs. 

I am trying your script python phyluce_dupe_contig_parser.py however, I keep getting the below error and I am unsure how to proceed. 

(UCEs) [deco313@login1 all]$ python phyluce_dupe_contig_parser.py --output dupes_all --contigs ../../All_contigs/test --dupes ../../DUPES --fasta all-taxa-incomplete.fasta --conf all-taxa-incomplete_dupe.conf --incomplete all-taxa-incomplete.incomplete
Working on ANT170
Traceback (most recent call last):
  File "phyluce_dupe_contig_parser.py", line 242, in <module>
    main(args)
  File "phyluce_dupe_contig_parser.py", line 195, in main
    (added_loci, a) = generateconseq()
  File "phyluce_dupe_contig_parser.py", line 170, in generateconseq
    align = AlignIO.read(outfile, "fasta")
  File "/ichec/home/users/user/.conda/envs/UCEs/lib/python2.7/site-packages/Bio/AlignIO/__init__.py", line 428, in read
    raise ValueError("No records found in handle")
ValueError: No records found in handle

**Comment by MikeWLloyd** [comment]
This seems like it could be similar to issue #1. It could be due to the headers within your data differing from expectation. Look through the comments in the other issue, and see if anything there can help. I unfortunately do not have time to troubleshoot this script.

**Comment by Deco313** [comment]
Thank you, that is running now
